# Generated by Django 2.2.9 on 2020-01-10 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200109_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 16, 50, 36, 763853), verbose_name='date published'),
        ),
    ]
